import type { Metadata } from "next";
import ModeToggle from '@/components/ui/darkmodeToggle'
import { ThemeProvider } from "@/components/theme-provider"
import { Inconsolata } from "next/font/google";
import "./globals.css";

const inconsolata = Inconsolata({
	variable: "--font-inconsolata",
	style: "normal"
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${inconsolata.variable} ${inconsolata.variable} antialiased`}
			>
				{/* <ModeToggle></ModeToggle> */}
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
