import "./globals.css";
import Nav from "@/components/ui/navbar";
import localFont from 'next/font/local'
import type { Metadata } from "next";

const regularIosevka = localFont({
	src: [
		{
			path: "./fonts/IosevkaNerdFontMono-Regular.ttf",
			style: "normal"
		},
		{
			path: "./fonts/IosevkaNerdFontMono-Italic.ttf",
			style: "italic"
		},
	]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${regularIosevka.className} antialiased`}
			>
				<Nav></Nav>
				{children}
			</body>
		</html>
	);
}
